from main import *

class TestStates(StatesGroup):

    mail = State()
    photo = State()
    qiwi = State()
    card = State()
    youmoney = State()
    bitcoin = State()
    withdrawal = State()
    user_ban = State()
    user_unban = State()
    user_increase_balance = State()
    user_decrease_balance = State()
    promo = State()
    promo_max = State()
    promo_percent = State()
    voucher = State()
    add_admin = State()
    delete_admin = State()
    delete_promo = State()
    delete_voucher = State()
    amount = State()
    requisites = State()
    requisites_v1 = State()
    activate_promo = State()
    activate_voucher = State()
    crystalpay = State()

